# Generated by Django 5.0 on 2025-02-05 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0038_checklist_checklisttemplate_checklisttask'),
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportrequest',
            name='ticket',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='helpdesk.ticket', verbose_name='Тикет'),
        ),
    ]
