volumes:
  pg_data:

services:
  db:
    image: postgres:16
    container_name: hitalant_db
    env_file: 
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: always

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: 
      - .env
    image: mendeit/hitalant_backend
    container_name: hitalant_backend
    depends_on:
      - db
    volumes:
      - ./alembic:/app/alembic
    ports:
      - 8000:8000
