volumes:
  pg_data:

services:
  db:
    image: postgres:16-alpine
    container_name: fastapibot_db
    env_file: 
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./app
      dockerfile: Dockerfile
    image: mendeit/fastapibot
    container_name: fastapibot_backend
    env_file: 
      - .env
    depends_on:
      - db
